### PR TITLE
Add support for Laravel 6, 7 & phpunit up to 8

### PR DESCRIPTION
**Pull request by jkudish**
Hey there :)

Attempting an upgrade to Laravel 6.0+ here 👍

### CODE REVIEW

**Comment by jkudish** [comment]
@tylercd100  can you merge this so we don't have to maintain a fork, please?

**Comment by KieronWiltshire** [comment]
update?

**Comment by jkudish** [comment]
@tylercd100 hey, can you please merge this?

**Comment by kyranb** [comment]
@tylercd100 Any chance this can be merged in?

**Pull request merged**
